# Generated by Django 4.2.21 on 2025-08-28 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Nombre del Proyecto a crear', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Descripcion del Proyecto a crear', max_length=255, verbose_name='Descripcion')),
                ('estado', models.CharField(choices=[('PL', 'Planeación'), ('P', 'En Proceso'), ('C', 'Completado')], default='PL', max_length=2, verbose_name='Estado')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicoProyecto', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioProyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
