# Generated by Django 4.2.21 on 2025-09-04 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Proyecto a crear', max_length=255, verbose_name='Nombre')),
                ('cliente', models.CharField(help_text='Cliente del Proyecto', max_length=255, verbose_name='Cliente')),
                ('descripcion', models.TextField(help_text='Descripción del Proyecto', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PL', 'Planeación'), ('P', 'En Proceso'), ('C', 'Completado')], default='PL', max_length=2, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INF', 'Infraestructura'), ('OBM', 'Obras de Mitigación'), ('ALC', 'Alcantarillado'), ('CMRV', 'Construcción y Mantenimiento de Red Vial')], default='S', max_length=4, verbose_name='Tipo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgProjects/', validators=[project.models.validate_image_size, project.models.validate_image_extension], verbose_name='Imagen Proyecto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicoProyecto', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioProyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
