# Generated by Django 4.2.21 on 2025-09-07 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='cliente',
            field=models.CharField(max_length=150, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.ImageField(default='imgProjects/placeholder.jpg', upload_to='imgProjects/', validators=[project.models.validate_image_size, project.models.validate_image_extension], verbose_name='Imagen Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField( max_length=60,
            choices=[('AL', 'Alcantarillado'), ('OBM', 'Obras de Mitigación'), ('CMV', 'Construcción y Mantenimiento de Red Vial'), ('INF', 'Infraestructura')], verbose_name='Tipo de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
    ]
