# Generated by Django 4.2.21 on 2025-09-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='\\imgProjects', verbose_name='Imagen Proyecto'),
        ),
    ]
