# Generated by Django 4.2.21 on 2025-09-07 22:24

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_alter_project_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgProjects/', validators=[project.models.validate_image_size, project.models.validate_image_extension], verbose_name='Imagen Proyecto'),
        ),
    ]
