# Generated by Django 4.2.21 on 2025-09-09 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_project_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo técnico a almacenar.', upload_to=project.models.archivos_project_path)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve o notas del archivo (opcional).')),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original con el que fue subido el archivo.', max_length=255)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME (por ejemplo, application/pdf).', max_length=100)),
                ('tamano_bytes', models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes.')),
                ('subido_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de carga.')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece el archivo.', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='project.project')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió el archivo.', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo técnico',
                'verbose_name_plural': 'Archivos técnicos',
                'ordering': ['-subido_en'],
                'indexes': [models.Index(fields=['project', '-subido_en'], name='project_arc_project_fe886d_idx'), models.Index(fields=['mime_type'], name='project_arc_mime_ty_1b5c4a_idx'), models.Index(fields=['subido_por'], name='project_arc_subido__11abdb_idx')],
            },
        ),
    ]
