# Generated by Django 4.2.21 on 2025-09-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_archivotecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotecnico',
            name='archivo',
            field=models.FileField(help_text='Archivo técnico a almacenar.', max_length=500, upload_to=project.models.archivo_tecnico_upload_to),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='nombre_original',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='project.project'),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='subido_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivotecnico',
            name='tamano_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
